apiVersion: apps/v1
kind: Deployment

metadata:
  name: $COMPONENT
  labels:
    app.kubernetes.io/name: $COMPONENT
    app.kubernetes.io/instance: $COMPONENT
    app.kubernetes.io/version: latest
    app.kubernetes.io/component: 5g
    app.kubernetes.io/part-of: oai
    app.kubernetes.io/managed-by: oai

spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: $COMPONENT
      app.kubernetes.io/instance: $COMPONENT
      app.kubernetes.io/version: latest
      app.kubernetes.io/component: 5g
  template:
    metadata:
      labels:
        app.kubernetes.io/name: $COMPONENT
        app.kubernetes.io/instance: $COMPONENT
        app.kubernetes.io/version: latest
        app.kubernetes.io/component: 5g
        app.kubernetes.io/part-of: oai
        app.kubernetes.io/managed-by: oai
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      hostname: ${COMPONENT}-1
      subdomain: oai
      containers:
      - name: main 
        image: $IMAGE
        imagePullPolicy: Always
        command:
        - tail
        - -f
        - /dev/null  
        resources:
          requests:
            cpu: 4
            memory: "8Gi"
          limits:
            cpu: 4
            memory: "8Gi"
        volumeMounts: 
          - name: ${COMPONENT}-cfg 
            mountPath: /oai/etc/${COMPONENT}.conf
            subPath: ${COMPONENT}.conf
          - name: usrp
            mountPath: /dev/bus/usb/
          - name: cpu
            mountPath: /sys/devices/system/cpu/
          - name: cgroup
            mountPath: /sys/fs/cgroup/
          - name: cstate
            mountPath: /dev/cpu_dma_latency
        securityContext:
          privileged: true 
          capabilities:
            add: ["SYS_ADMIN","SYS_NICE","SYS_RAWIO","IPC_LOCK"]
            #nodeSelector:
            #kubernetes.io/hostname: hack-things
      schedulerName: default-scheduler
      volumes:
      - name: ${COMPONENT}-cfg
        configMap:
          name: ${COMPONENT}-oai
      - name: cgroup
        hostPath:
          path: /sys/fs/cgroup/
      - name: usrp
        hostPath:
          path: /dev/bus/usb/
      - name: cpu
        hostPath:
          path: /sys/devices/system/cpu/
      - name: cstate
        hostPath:
          path: /dev/cpu_dma_latency
