apiVersion: apps/v1
kind: Deployment

metadata:
  name: $COMPONENT
  labels:
    app.kubernetes.io/name: $COMPONENT
    app.kubernetes.io/instance: $COMPONENT
    app.kubernetes.io/version: latest
    app.kubernetes.io/component: 5g
    app.kubernetes.io/part-of: oai
    app.kubernetes.io/managed-by: oai

spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: $COMPONENT
      app.kubernetes.io/instance: $COMPONENT
      app.kubernetes.io/version: latest
      app.kubernetes.io/component: 5g
  template:
    metadata:
      labels:
        app.kubernetes.io/name: $COMPONENT
        app.kubernetes.io/instance: $COMPONENT
        app.kubernetes.io/version: latest
        app.kubernetes.io/component: 5g
        app.kubernetes.io/part-of: oai
        app.kubernetes.io/managed-by: oai
    spec:
      hostname: ${COMPONENT}-1
      subdomain: oai
      containers:
      - name: main 
        image: $IMAGE
        imagePullPolicy: Always
        #command:
        #- tail
        #- -f
        #- /dev/null  
        volumeMounts: 
          - name: ${COMPONENT}-cfg 
            mountPath: /oai/etc/${COMPONENT}.conf
            subPath: ${COMPONENT}.conf
          - name: usrp
            mountPath: /dev/bus/usb/
          - name: cgroup
            mountPath: /sys/fs/cgroup/
        securityContext:
          privileged: true # HACK to enable "/dev/net/tun"
      nodeSelector:
        kubernetes.io/hostname: kind-worker
      volumes:
      - name: ${COMPONENT}-cfg
        configMap:
          name: $COMPONENT
      - name: cgroup
        hostPath:
          path: /sys/fs/cgroup/
      - name: usrp
        hostPath:
          path: /dev/bus/usb/